### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by gopi2904** [konradsemsch/ggrapid#2]
devtools::install_github("konradsemsch/ggrapid")
Downloading GitHub repo konradsemsch/ggrapid@master
Installing 22 packages: extrafont, formattable, hrbrthemes, paletteer, extrafontdb, Rttf2pt1, gdtools, gameofthrones, ggthemes, jcolors, oompaBase, harrypotter, palr, pals, scico, systemfonts, maps, dichromat, mapproj, rgl, manipulateWidget, miniUI
Error: Failed to install 'ggrapid' from GitHub:
  (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6/PACKAGES'

**Comment by konradsemsch** [comment]
Hmmm, I'm actually not quite sure what this could be concerning. Could you provide some more information such as session info for example?

**Comment by gopi2904** [comment]
Thank you. That was a temporary glitch encountered while installing ggrapid. The issue was resolved.
